name: signalr_core
description: ASP.NET Core SignalR Client written for Dart that is platform-independent, and can be used on both the command-line and the browser.
version: 1.1.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.2
  logging: ^1.2.0
  meta: ^1.10.0
  tuple: ^2.0.2
  web_socket_channel: ^2.4.0
  sse_channel:
    path: ../sse_channel
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4